-   name:   Asegurar que nginx est치 instalado en la versi칩n solicitada
    apt:
        name: "nginx={{ nginx.version }}" 
        state: present
    tags:
        - INSTALACION
    
-   name:   Asegurar que nginx tiene la configuraci칩n adecuada
    notify: CAMBIO_CONFIGURACION
    template:
        src:        templates/nginx.conf
        dest:       /etc/nginx/sites-available/default
        mode:       '0644'
        force:      true
        backup:     true
    tags:
        - CONFIGURACION

-   name:   Asegurar que tengo servicio de nginx est치 arrancado
    service:
        name:       nginx
        state:      started
        enabled:    true
    notify: SERVICIO_INICIADO
    tags:
        - ARRANQUE
        - INSTALACION